### PR TITLE
Reed Turgeon - User Interface Project Week

### PR DESCRIPTION
**Pull request by MrT3313**

### CODE REVIEW

**Comment by MrT3313** [comment]
^ = 45 min pomodoro (with some slow setup @ the start)

**Comment by MrT3313** [comment]
^ = 45 min pomodoro

**Comment by MrT3313** [comment]
^ = 30 min pomodoro

**Comment by MrT3313** [comment]
^ = 30 min pomodoro

**Comment by MrT3313** [comment]
^ = 30 min pomodoro

**Comment by MrT3313** [comment]
^ --> both commits = 30 min pomodoro

**Comment by MrT3313** [comment]
^ = 30 min pomodoro

**Comment by MrT3313** [comment]
^ = 3x (30min pomodoro)

**Comment by MrT3313** [comment]
^ = 45 min

**Comment by MrT3313** [comment]
^ = 30min

**Comment by MrT3313** [comment]
^ = 45 min

**Comment by MrT3313** [comment]
^ = 15 min

**Comment by MrT3313** [comment]
^ = A LONG TIME

**Comment by gsamaniego41** [comment]
## MVP Features:
These MVP features represent the fundamental knowledge you should have obtained throughout the last 4 weeks.  If you cannot accomplish all of the MVP tasks listed here, you may be a candidate for the mastery based program.
* [x] Build layout **HTML/LESS**: [Home page desktop design](/DesignFiles/Home/home-desktop.png)
* [x] Build layout **HTML/LESS**: [Home page mobile design](/DesignFiles/Home/home-mobile.png)
* [ ] Build layout **HTML/LESS**: [Services page **desktop design only**](/DesignFiles/Services/services-desktop.png)
* [ ] Build layout **HTML/LESS/JavaScript**: [Navigation system design](DesignFiles/Navigation)
	* [Non-expanded View Design](DesignFiles/Navigation/non-expanded/non-expanded.png): When the navigation is not active, it should be fixed to the top of the page at all times
	* [Expanded View Design](DesignFiles/Navigation/expanded): When a user clicks on the navigation icon a full page overlay will pop over all the content on the page. The navigation icon will be replaced by a close icon. The user must click the close icon to return back to browsing the website. The home and services pages need to be linked together using `<a></a>` tags. You must use your own custom JavaScript for the opening and closing functionality, no bootstrap allowed for functionality on this feature
* [x] Build Custom Component **HTML/LESS/JavaScript**: [Services page tab navigator design](/DesignFiles/Services/tabs)
	* [Using the assets provided](/img/services), you must build the tab navigator using your own custom JavaScript component, no libraries allowed on this feature. You are encouraged to use code from previous weeks to accomplish this feature

**Pull request merged**
